#Configurado pra rodar banco sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.url=jdbc:sqlite:lib-musical.db

spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

#chave genérica pra teste
jwt.secret=Y29tLmxpYm11c2ljYWwuYXBpLnNlY3VyaXR5LnRva2VuLnNlY3JldC5rZXkuZ2VuZXJhdGVkLjIwMjY=